---
settings:
  name: Azure NetApp Files
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: fr-fr,us-en,de-de,es-es,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentation Azure NetApp Files
    url: "/index.html"
  - title: Notes de mise à jour
    entries:
    - title: Quoi de neuf
      url: "/whats-new.html"
  - title: Commencez
    entries:
    - title: Découvrez Azure NetApp Files
      url: "/concept-azure-netapp-files.html"
    - title: Mise en route du flux de travail
      url: "/task-quick-start.html"
    - title: Configurez une application Microsoft Entra
      url: "/task-set-up-azure-ad.html"
    - title: Créer un environnement de travail
      url: "/task-create-working-env.html"
  - title: Utiliser Azure NetApp Files
    entries:
    - title: Création et montage de volumes
      url: "/task-create-volumes.html"
    - title: Gérer les volumes existants
      url: "/task-manage-volumes.html"
    - title: Déposer Azure NetApp Files
      url: "/task-remove-working-env.html"
  - title: Connaissances et support
    entries:
    - title: S'inscrire pour obtenir de l'aide
      url: "/task-support-registration.html"
    - title: Obtenez de l'aide
      url: "/task-get-help.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
